services:
  #  Database
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: abc123
    networks:
      -  wpsite
    expose:
      -  3306
      -  33060

  #  Wordpress
  wordpress:
    depends_on:
      -  db
    image: wordpress:latest
    ports:
      -  '80:80'
    restart: always
    volumes: 
      -  wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: abc123
      WORDPRESS_DB_NAME: wordpress
    networks:
      -  wpsite

networks:
  wpsite:

volumes:
  db_data:
  wp_data: